language: node_js
node_js:
  - "10"
branches: 
  only:
    - "master"
install:
  - "npm install"
  - "npm install -g codecov"
script:
  - "npm run test"
  - "codecov"
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  cleanup: false
  on:
    tags: true
    branch: master
  tag: latest