language: node_js
node_js:
  - "10"
brancher: 
  only:
    - "master"
install:
  - "npm install"
  - "npm install -g codecov"
script:
  - "npm run test"
  - "codecov"
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    tags: true
    branch: master
  tag: latest
  condition: '$TRAVIS_TAG =~ ^v[0-9]+.[0-9]+.[0-9]+$'